- src/ansys/openapi/common/_oidc.py
Fix for a deadlock where we try to kill the callback server when it's already shut itsself down.
Also correct the name of the audience header required by Auth0, opaque tokens are sometimes not supported by APIs and this causes Auth0 to actually return us a JWT.
> OIDC Deadlock Fix

- src/ansys/openapi/common/__init__.py
- src/ansys/openapi/common/_api_client.py
- src/ansys/openapi/common/_session.py
- tests/test_api_client.py
Remove api_client's header interface, rely on SessionConfiguration
- Remove header related properties
- Create default session configuration if absent
- Add default user-agent if missing
- Remove tests for removed properties
> Rationalise Header Behaviour

- .github/workflows/ci_cd.yml
Updates the release workflow with the placeholder for the twine token and enforces noninteractive mode to prevent hangs if something goes wrong.
> Add token for twine release

- pyproject.toml
- src/ansys/openapi/common/_oidc.py
- src/ansys/openapi/common/_util.py
- tests/test_utils_misc.py
Closes #137 
The OIDCCallbackHTTPServer wasn't correctly releasing TCP port 32284. This caused problems if we tried to authenticate to a second OIDC server in the same script, e.g. by using the STK.
This PR re-works the OIDCCallbackHTTPServer implementation to use `handle_request()` instead of `serve_forever()`, which seems to eliminate the need to run the server in a separate thread. Instead, we now synchronously wait the `login_timeout` length of time for the server to handle a request. If it does, we return the auth_code.
I have also added tests that check the status of the TCP port both when the server is running and when it has been closed.
> Ensure OIDC Callback Server releases bound TCP port

- pyproject.toml
- tests/test_utils_misc.py
Closes #141 
This PR checks that an OIDC callback server is running and bound to the required port before proceeding with tests. This fixes an intermittent issue where a test to check the port was bound would fail if the server hadn't start.
This change in effect allows multiple attempts to check that the port is bound. However, it still requires that the port release happens strictly sequentially after the request is made, which is the most important part of the test.
> Fix flaky OIDC test

- .github/workflows/ci_cd.yml
The workflow previously downloaded the pdf documentation and wheel file into `~/`. The twine release step tries to find a wheel with the glob `~/**/*.whl` which matches any wheel in any subdirectory. It was not matching.
> Fix release workflow

- src/ansys/openapi/common/_session.py
- tests/test_missing_imports.py
Closes #145 
Changes the name of the package in the pip command. The text can now be copied as-is to the command line to install the necessary packages. I have also fixed the similar linux-kerberos exception text.
> Fix missing OIDC components exception message

- .github/workflows/ci_cd.yml
Closes #156 
Add the generate_release_notes flag to the release action to automatically add release notes
> [CI]156 - Add generate_release_notes to release action

- src/ansys/openapi/common/_api_client.py
- tests/test_api_client.py
- tests/test_integration_anonymous.py
- tests/test_integration_basic.py
- tests/test_integration_negotiate.py
Closes #171 
Accompanying code generator generates path parameters with placeholder values like `http://api.com/resource/{param}`, this was being incorrectly handled, resulting in invalid resources.
This PR is some minor refactoring to improve testability, adding some tests for path and query parameter construction, and the fix for the underlying issue.
> 171 - Fix path parameter format

- poetry.lock
- pyproject.toml
- src/ansys/openapi/common/_session.py
Bumping sphinx unblocks requests, which then triggers a new version of the requests type stubs. These are now more strict, and so we need to match them in the signature for our RetryAdapter.
> Bump sphinx to 4.5.0 and fix signature for RetryAdapter

- README.rst
Closes #162 
This PR makes the readme documentation self-consistent. All methods referred to have leading .s.
> 162 - Make Syntax Consistent in docs for Auth Types 

- src/ansys/openapi/common/_api_client.py
- tests/test_api_client.py
Closes #170 
This PR treats response data as a string if it's specified as str, even if it looks like json.
Sometimes APIs will return stringified json, currently this will throw when we attempt to deserialize it, since we will end up expecting a string but we will receive a dictionary. This PR makes response_type override the existing logic, so that this use case is supported.
> 170 - Respect response_type when Deserializing response

- src/ansys/openapi/common/__init__.py
- src/ansys/openapi/common/_util.py
MYPY gets quite confused when we need to import packages conditionally, for example importlib-metadata backport for python 3.7. If we specify a version switch, rather than trying and excepting on the ImportError then MYPY is intelligent enough to not verify typings for branches that cannot be hit.
This PR should fix the issue with the Keyring Dependabot PR, and hopefully should stop the ping-pong adding a removing the ignore flag in `__init__.py`
> FIX - Make explicit which imports are expected on each version

- doc/source/conf.py
This PR adds the language tag to conf.py. Absence of this will be a warning in sphinx 5, which will cause doc build failures (see https://github.com/pyansys/openapi-common/actions/runs/2859407707)
> Add language to conf.py

- pyproject.toml
Build is currently broken, I'm not sure exactly why, but the behaviour of the `poetry install` command changed, and it looks like we were relying on some unsupported functionality.
The `[testenv].extras` property is supported correctly in tox and this appears to fix the issue locally.
> CI - Use explicit extras syntax for tox-poetry

- src/ansys/openapi/common/_api_client.py
- tests/test_api_client.py
Closes #284 
This PR ensures that query parameters are converted to strings before we try to concatentate them into the actual query string.
Uses implicit string conversion via an f-string for clarity.
> #284 - Convert Query Params to Strings

- .github/workflows/ci_cd.yml
Closes #281 
This PR adds the documentation build and packaging steps for the dev portal. Does not currently push those changes to the appropriate branch for publishing, but stores them as a build artefact.
Based on work in https://github.com/pyansys/pyaedt/pull/1747/files
> #281 - Output documentation for dev portal

- src/ansys/openapi/common/_oidc.py
- tests/test_oidc.py
Closes #224 
This PR adds a couple tests to ensure that the token is logged when requested to.
> #224 Add tests for token logging

- doc/source/conf.py
Closes #292 
This PR changes the copyright date in docs to be the current year. Also changed config to use `project_copyright` instead of `copyright`
> #292 - Update copyright date

- doc/source/api/index.rst
- doc/source/conf.py
- src/ansys/openapi/common/_api_client.py
Closes #152 
- Add type aliases to the docs
- Add xref configuration for typing module, so that cross docs links are correctly generated in docstrings
> #152 Docs: add type aliases to docs

- doc/source/conf.py
- poetry.lock
- pyproject.toml
This PR removes the dependency on sphinx_autodoc_typehints. It was only used for removing typehints from signatures in the docs, which is now achieved by sphinx.ext.autodoc
I've checked the generated docs manually and the output is identical.
> Docs - Remove sphinx_autodoc_typehints dependency

- CONTRIBUTING.md
- README.rst
- doc/.vale.ini
- doc/source/api/index.rst
- doc/source/contributing.rst
- doc/source/index.rst
- doc/styles/.gitignore
- doc/styles/Vocab/ANSYS/accept.txt
- src/ansys/openapi/common/_util.py
@Andy-Grigg I've performed an overall doc review. However, I don't know where the "shared components" text comes from. I've used the convention OpenAPI-Common as the library name to match the convention for other PyAnsys libraries. I will need to do this in the Shared Components content. There also seems to be a good bit of redundant but unused information in the small number of files for this repository.
Lastly, I copied in Vale folders/files, but Vale will still need to be implemented as part of the CI/CD process. I thought having the folders/files there would save you a step or two.
> Review doc content

- src/ansys/openapi/common/_api_client.py
- src/ansys/openapi/common/_base/_types.py
- tests/test_api_client.py
Closes #311 
This PR adds a new parameter to `call_api`, so that auto-generated API method code can specify different response types for each response status codes
> Add response type mapping for response deserializing

- poetry.lock
- src/ansys/openapi/common/_exceptions.py
- src/ansys/openapi/common/_session.py
- tests/test_exceptions.py
- tests/test_integration_basic.py
- tests/test_integration_negotiate.py
- tests/test_session_creation.py
Closes #313 
Improves the message included in an ApiConnectionException to include all the information that is passed into the exception constructor, instead of just the response from the server.
Also adds the URL that resulted in the exception, resulting in a stack trace that looks like this:
```
Traceback (most recent call last):
File "C:\Users\<username>\AppData\Roaming\JetBrains\PyCharm2022.2\scratches\scratch_5.py", line 6, in <module>
conn = ApiClientFactory(api_url=url).with_credentials(**creds).connect()
File "C:\git\pyansys\openapi-common\src\ansys\openapi\common\_session.py", line 213, in with_credentials
if self.__test_connection():
File "C:\git\pyansys\openapi-common\src\ansys\openapi\common\_session.py", line 317, in __test_connection
raise ApiConnectionException( …
```
> Include more details in the ApiConnectionException message

- src/ansys/openapi/common/_exceptions.py
In PR #316 we changed the structure of the ApiConnectionException, but we did not change the docstring.
This PR changes the docstring to reflect the changes to the class.
> Fix ApiConnectionException docstring

- .github/workflows/ci_cd.yml
Closes #326 
This PR removes the docs build for JSON format, this should unblock the sphinx-theme update, as well as removing some magic bash scripts.
> CI - Remove JSON docs publishing

- .github/workflows/ci_cd.yml
Recent update to poetry has switched to a new "modern" installer. This strictly validates package compliance to PEP-627 and ensures that every file other than optional `.pyc` and the `RECORD` file have correct hashes.
Unfortunately for use `sphinx-theme-builder` currently fills this file with nonsense hashes when generating the theme files for `pydata-sphinx-theme` and so poetry is refusing to install it. I have some sympathy with the poetry devs, unlike the rather rude contributor who made the upstream fix, however this seems to not be a release priority for the maintainer of `sphinx-theme-builder`.
This PR makes the workaround of reverting to the old installer in the one CI step where we actually use this dependency.
> CI - Workaround for pydata-sphinx-theme invalid wheel

- .github/workflows/ci_cd.yml
- doc/source/conf.py
With the move to the Ansys org, github packages have changed namespace. This PR updates the CI step that requires the package.
> CI - Use Ansys package repo

- README.rst
Fix name of build-essential package and add note about sourcing python3.10
> Fix Ubuntu 2004 Instructions

- doc/source/conf.py
- src/ansys/openapi/common/__init__.py
- src/ansys/openapi/common/_base/_types.py
- src/ansys/openapi/common/_oidc.py
Run linter with new black and commit changes
> Lint project with black 24.1.1

- .github/workflows/ci_cd.yml
Closes #458
Uses Ansys actions to build, smoke test (i.e. build wheelhouses) and publish to PyPI and GitHub. This should resolve the GitHub release file attachment issue, although it's difficult to tell without actually releasing. Using 'dry-run' mode on the action looks good though.
The doc publishing is still manual, since we'll need to migrate openapi-common to versioned docs to do that. That's a much larger job.
> Use more PyAnsys actions

- .github/workflows/ci_cd.yml
Fix release doc publish failure by adding checkout step to workflow.
I don't think we actually need to checkout this repo, but this is a convenient way of making sure git is setup and authenticated correctly.
Once this is merged I will cherrypick to the release/1.5 branch and try another rc
> Add checkout step to doc deploy job

- src/ansys/openapi/common/_oidc.py
- tests/test_oidc.py
Closes #570
Azure AD returns authority URLs without a trailing slash. We had naively been doing some string formatting to make this work, instead we should properly construct the well-known URL.
Add a couple of additional test cases here including a url with a path segment, and one without a trailing slash.
> FIX - 570 - Add handling for authority URLs with no trailing slash

- .github/workflows/ci_cd.yml
- .github/workflows/label.yaml
- CHANGELOG.md
- doc/changelog.d/563.changed.md
- doc/changelog.d/changelog_template.jinja
- pyproject.toml
Add the doc-changelog action to update the markdown file as per instructions at:
https://actions.docs.ansys.com/version/stable/migrations/docs-changelog-setup.html#docs-changelog-action-setup
> 548 - CI - Add doc-changelog action

- CHANGELOG.md
- doc/changelog.d/576.changed.md
Manually update changelog for recent releases. For future releases, this should be handled automatically by towncrier
> Manually update changelog for 2.0.0 and 2.0.1 releases

- .github/workflows/ci_cd.yml
- doc/changelog.d/577.changed.md
- doc/source/conf.py
Change CNAME to `openapi.docs.pyansys.com`
> Update CNAME to support publishing documentation from this repository

- .github/workflows/ci_cd.yml
- doc/Makefile
- doc/changelog.d/580.changed.md
- pyproject.toml
Remove -j args
Remove blank line
> Remove documentation build parallel execution arguments

- .github/labels.yml
- .github/workflows/label.yaml
- doc/changelog.d/581.changed.md
Closes #582 
The labelling workflow currently runs on pushes to main. This should only happen if the labels.yml file (which is also missing) is updated.
This PR makes the following changes:
* Add the label definition, copied from grantami-recordlists
* Only trigger on pushes to main if the label definition is modified
* Only run the labeler step for pull requests (i.e. not for pushes)
Assuming this works as expected, we should copy these changes to the other repos
> Fix labelling workflow

- .github/workflows/label.yaml
- doc/changelog.d/587.changed.md
Closes #586 
Skips generation of changelog fragments for dependabot PRs
> Don't generate changelog fragments for dependabot PRs

- .github/workflows/dependabot_approve.yml
Fix dependabot auto-approve workflow by deleting unnecessary workflow step.
This step isn't used for anything, but fails for a non-dependabot PR.
> Fix dependabot-autoapprove workflow

- .github/workflows/ci_cd.yml
- doc/changelog.d/646.maintenance.md
Closes #598 
Use Trusted Publisher instead of the previous token approach. I have defined an environment that:
* Requires approval from one other member of the maintainer team
* Only runs from a release/* branch
> Use PyPI Trusted Publisher approach for releases

- .github/workflows/ci_cd.yml
- doc/changelog.d/648.maintenance.md
Fixes the syntax used to provide the token to the doc-deploy-changelog action. This mirrors the fix made directly in the release/2.1 branch.
> Fix GitHub Actions syntax for doc-deploy-changelog action

- doc/changelog.d/651.fixed.md
- doc/source/conf.py
- doc/source/contributing.rst
- doc/styles/config/vocabularies/ANSYS/accept.txt
- src/ansys/openapi/common/_session.py
Closes #650 
This PR solves the problem of 'leaking' ansys.openapi.common documentation specifics into packages that subclass the types in this package.
Missing xrefs in numpydoc docstrings was fixed by fully qualifying type references in docstrings for all commonly inherited classes and add a note in the contributing guide.
This is achieved by wrapping `.. versionadded::` ReStructuredText directives in a pair of `.. only::` blocks that serve to switch the documentation behavior depending on whether a tag is present or not. If the tag is present, it is assumed that we are building 'standalone' docs, i.e. docs for this package, and the versionadded directive is included. If the tag is not present, it is assumed we are building docs for some other package that inherit docstrings from this …
> Allow packages to build documentation if they inherit classes in this package

- .github/workflows/ci_cd.yml
- doc/changelog.d/674.dependencies.md
- poetry.lock
- pyproject.toml
Remove support for 3.9 and the classifier from pyproject.toml and remove from CI setup
> Drop support for Python 3.9

- README.rst
- doc/changelog.d/696.documentation.md
In #649 we suggest using pip-system-certs, this PR adds a documentation note to the readme guiding users to use the library.
It does not add the dependency, to an extra or otherwise, given concerns over side-effects etc.
> Add a documentation note about pip-system-certs

- doc/changelog.d/699.maintenance.md
- pyproject.toml
There were no dev docs published with version 2.2, so they're still on 2.1 which is a bit confusing. This bumps the version to 2.3.
> Bump version to 2.3

- README.rst
- doc/source/conf.py
- doc/source/contributing.rst
- doc/source/getting_started/index.rst
- doc/source/index.rst
- doc/source/user_guide/index.rst
- doc/styles/config/vocabularies/ANSYS/accept.txt
- poetry.lock
- pyproject.toml
Closes #705
This PR was originally going to just include the README in the HTML documentation, but I realize the HTML documentation differs significantly from the other PyAnsys documentation styles in terms of structure, so I took this opportunity to re-organize things.
The PyAnsys approach is to include minimal info in the README, limited mainly to installation and getting started. The docs now mirror that approach, and use a sphinx-design gallery to link to other locations. The content from the README has moved to a new User Guide document, which describes how to use openapi-common.
> Reorganize documentation

- .github/workflows/ci_cd.yml
- doc/changelog.d/761.maintenance.md
Fixes #760 
The documentation for the release-github action shows that the token parameter is required: https://actions.docs.ansys.com/version/stable/release-actions/index.html#release-github-action
We presumably missed this change to the action because we release from this repository relatively rarely.
Once this is merged, it should be cherry-picked onto the release/2.2 branch.
> Add token to GitHub release CI

- doc/changelog.d/773.added.md
- src/ansys/openapi/common/_oidc.py
- src/ansys/openapi/common/_session.py
- src/ansys/openapi/common/_util.py
- tests/test_oidc.py
- tests/test_session_creation.py
We currently only support providing a refresh token for OIDC use, this is certainly a more robust solution but not all IDPs and deployments are configured to allow the `offline_access` scope, and sometimes we do not have access to a refresh token at all.
This PR allows users to provide an access token for short-lived scripts.
> Support OIDC with a provided Access Token

- .github/workflows/ci_cd.yml
- doc/changelog.d/777.maintenance.md
Latest versions of the source action prevent it being used in reusable workflows, so ansys actions have removed support from their publish action. Replace this with the source action directly in our release job.
> Revert to pypa/gh-action-pypi-publish for publishing

- CHANGELOG.md
- doc/changelog.d/698.maintenance.md
- doc/changelog.d/699.maintenance.md
- doc/changelog.d/706.documentation.md
- doc/changelog.d/709.documentation.md
- doc/changelog.d/759.maintenance.md
- doc/changelog.d/763.maintenance.md
- doc/changelog.d/771.maintenance.md
- doc/changelog.d/773.added.md
- doc/changelog.d/777.maintenance.md
- doc/changelog.d/778.added.md
- doc/changelog.d/782.miscellaneous.md
Revert the changelog deployment for the 2.3 release branch
> Revert chore: updating CHANGELOG for v2.3.0

- .github/workflows/ci_cd.yml
- doc/changelog.d/781.maintenance.md
The env var for the package name is `LIBRARY_NAME` which is not the one in the pyansys migration guide. This made the attempted release of 2.3 fail.
> Fix release action environment variable

- .github/workflows/ci_cd.yml
- .github/workflows/dependabot_approve.yml
- .github/workflows/label.yaml
- doc/changelog.d/795.maintenance.md
Closes #794 
All actions are pinned to the latest available version, except for ansys/actions which are pinned to v9.0.9. See https://github.com/ansys/actions/issues/814 for cause.
> Use commit SHA to pin action versions

- .github/workflows/ci_cd.yml
- .github/workflows/label.yaml
- doc/changelog.d/801.maintenance.md
We have a number of security warnings around the default GITHUB_TOKEN permissions in this repository's CI. This PR sets a more restrictive set of permissions, which can then be extended as required for individual jobs.
> Set more restrictive workflow permissions

- doc/changelog.d/834.miscellaneous.md
- pyproject.toml
We currently don't have a dev suffix on the version number on main. This may be causing issues with the docs, where the `dev` option doesn't seem to be updating correctly.
> Bump version to v2.4.0.dev0

- .github/workflows/ci_cd.yml
- doc/changelog.d/835.miscellaneous.md
Documentation publishing is currently broken. I believe this is because we switched to using read permissions globally.
The documentation publishing jobs require write permissions to push the latest docs to the github-pages branch.
> Add write permissions for documentation publish jobs

- doc/changelog.d/849.miscellaneous.md
- src/ansys/openapi/common/_oidc.py
- tests/test_oidc.py
Closes #848 
When connecting to an API that requires a custom CA certificate we were not properly handling the session construction, so the OAuth handler provided with the internal CA bundle which was unlikely to allow SSL verification.
This PR improves the handling so the correct session configuration ends up on the correct session.
> FIX - Improve session management when creating OIDC clients

- .github/workflows/security_checks.yml
- doc/changelog.d/888.miscellaneous.md
Closes #883 
Closes #824 
Add a weekly workflow to check package vulnerabilities and to audit third-party actions.
> Add workflow to check dependencies and action security
