pyproject.toml
Bump version and trove classifier for release
=> Release OpenAPI-Common 1.0

pyproject.toml, src/ansys/openapi/common/_api_client.py, src/ansys/openapi/common/_contrib/granta.py
This PR tracks release activities for openapi-common version 1.1
=> Release Version 1.1

doc/source/conf.py, poetry.lock, pyproject.toml
This PR Switches the documentation to the new ansys-sphinx-theme to be in accordance with other PyAnsys packages
=> Switch Docs to Ansys Theme

LICENSE
This PR includes an end date for copyright declaration, covers contributions after the end of 2021
=> Update copyright date

.github/workflows/ci_cd.yml, doc/Makefile, poetry.lock, pyproject.toml
This PR replaces the test and doc extras with dependency groups.
=> #282 - Use dependency groups instead of dev only extras

.github/workflows/ci_cd.yml
This PR fixes tox invocation syntax for v4
=> Fix tox invocations for v4

.github/workflows/ci_cd.yml, doc/source/_static/README.md, doc/source/_templates/custom-class-template.rst, doc/source/_templates/custom-module-template.rst, doc/styles/Vocab/ANSYS/accept.txt
Uses the PyAnsys doc style check github action to check documentation style.
Adds required vocab and fixes some language in the current docs.
=> Add vale documentation check

.github/workflows/ci_cd.yml, doc/source/conf.py, pyproject.toml, src/ansys/openapi/common/_api_client.py
Backport changes introduced in #381 to the 1.2 release
Addresses #380
=> 1.2 - Backport performance improvement to 1.2

.github/workflows/ci_cd.yml, doc/source/index.rst, poetry.lock, pyproject.toml
Closes #427, dropping Python 3.8
Closes #335, issue with link in docs
=> Drop Python 3.8

src/ansys/openapi/common/_api_client.py, src/ansys/openapi/common/_base/_types.py, tests/models/__init__.py, tests/models/example_enum.py, tests/test_api_client.py
=> Feat: support enums

src/ansys/openapi/common/_oidc.py, tests/test_oidc.py
Removes undocumented environment flag
=> Remove verbose OIDC logging

pyproject.toml
Bump version to 1.4.0 for full release.
=> Maint: bump version to 1.4.0

AUTHORS.md, CHANGELOG.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, CONTRIBUTORS.md
Closes #455 
Adds additional required files to the repository root. Also back-populates the changelog.
=> Add repo files

pyproject.toml
=> Bump to 1.5.0rc0

.github/workflows/ci_cd.yml, pyproject.toml
=> Prepare for 1.5.0rc1 release

src/ansys/openapi/common/__init__.py, src/ansys/openapi/common/_api_client.py, src/ansys/openapi/common/_base/_types.py, tests/models/example_model.py, tests/test_api_client.py
This reverts commit 88655dc5ea34bd45c08091532f49b8a11d37ee8a.
=> Revert "Support optional fields in models (#497)"

CHANGELOG.md
=> DOCS - Add changelog entry for 1.5.1

CHANGELOG.md
Cherry picked from release/1.5
=> DOCS - Add changelog entry for 1.5.1 (#512)

.pre-commit-config.yaml, README.rst
Close #551 
Adds badges to the README
Configures pre-commit CI to open PRs to update hooks
=> Maint: pre-commit updates & badges

.github/dependabot.yml, .github/labeler.yml, .github/release.yml, .github/workflows/label.yaml
Closes #553 
- Fix links in comment added when no labels are found on a PR
- Use GH action for labelling
- Add bug fixes to release notes
- Label all dependabot PRs
=> Update labelling workflow

doc/changelog.d/578.changed.md, pyproject.toml
=> Bump version to 2.1.0

.github/workflows/label.yaml, doc/changelog.d/634.maintenance.md, pyproject.toml
Add missing parenthesis to labeller workflow.
=> Fix labeller workflow

doc/changelog.d/647.documentation.md, src/ansys/openapi/common/_session.py
Adds `versionadded` directives to new AuthenticationScheme enum and `with_credentials` parameter.
=> Add versionadded directives for new functionality

doc/changelog.d/651.fixed.md, doc/changelog.d/657.documentation.md, doc/source/conf.py, doc/source/contributing.rst, doc/styles/config/vocabularies/ANSYS/accept.txt, pyproject.toml, src/ansys/openapi/common/_session.py
Update version number and cherry-pick #651
=> Prepare 2.1.1 release

.github/workflows/ci_cd.yml, .github/workflows/label.yaml, doc/changelog.d/685.fixed.md
Add required user and email inputs for ansys actions
=> Add missing required inputs for v8 ansys/actions

.github/workflows/ci_cd.yml, doc/changelog.d/684.added.md, pyproject.toml
=> Add support for Python 3.13

.github/workflows/ci_cd.yml, doc/changelog.d/791.maintenance.md
Closes #788 
Add provenance attestations on wheelhouses and build artifacts.
=> Generate provenance attestations

doc/changelog.d/796.maintenance.md, pyproject.toml
Set version to 2.4.0 on the main branch.
=> Bump version to 2.4.0

doc/changelog.d/830.miscellaneous.md, poetry.lock
Update all dependencies in lock file
=> Update lock file

SECURITY.md, doc/changelog.d/831.miscellaneous.md
Closes #825 
Add SECURITY.md file
=> Add SECURITY.md file
